### ISSUE TITLE
2 months no progress?

### ISSUE THREAD

**Issue by WilliamBurdett** [pmwisdom/better-gh-actions#1]
Must be a dead repo! :+1: :-1: :100: :1st_place_medal: 

: D

**Comment by pmwisdom** [comment]
LOL

**Comment by pmwisdom** [comment]
<3

**Comment by pmwisdom** [comment]
Uh, this is the pinnacle of github actions, it needs no more work

**Comment by pmwisdom** [comment]
This will be closed since you haven't responded in the last 200ms
